document.getElementById('htmlcode').innerHTML = '`<pre class="hljs" style="display: block; overflow-x: auto; padding: 0.5em; background: rgb(240, 240, 240); color: rgb(68, 68, 68);"><span class="xml"><span class="hljs-meta" style="color: rgb(31, 113, 153);">&lt;!DOCTYPE html&gt;</span>
<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">html</span> <span class="hljs-attr">lang</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"en"</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">head</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">meta</span> <span class="hljs-attr">charset</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"UTF-8"</span> /&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">meta</span> <span class="hljs-attr">name</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"viewport"</span> <span class="hljs-attr">content</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"width=device-width, initial-scale=1.0"</span> /&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">title</span>&gt;</span>HelloToAll<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">title</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">link</span>
    <span class="hljs-attr">rel</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"stylesheet"</span>
    <span class="hljs-attr">href</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"</span>
		/&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">link</span> <span class="hljs-attr">rel</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"stylesheet"</span> <span class="hljs-attr">href</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"style.css"</span> /&gt;</span>
	<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">head</span>&gt;</span>
	<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">body</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"wrapper"</span>&gt;</span>
			<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">p</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"helloText"</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">span</span>&gt;</span>👨‍💻<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">span</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">span</span>&gt;</span>Hello to all<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">span</span>&gt;</span>
			<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">p</span>&gt;</span>
			<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"about-me"</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"mainText"</span>&gt;</span>I am<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">div</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">div</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"typedText"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">div</span>&gt;</span>
			<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">div</span>&gt;</span>
			<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">footer</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"social"</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"fa-brands fa-github"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">i</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"fa-brands fa-linkedin"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">i</span>&gt;</span>
				<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">i</span> <span class="hljs-attr">class</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"fa-brands fa-telegram"</span>&gt;</span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">i</span>&gt;</span>
			<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">footer</span>&gt;</span>
		<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">div</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">script</span> <span class="hljs-attr">src</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">script</span>&gt;</span>
		<span class="hljs-tag">&lt;<span class="hljs-name" style="font-weight: 700;">script</span> <span class="hljs-attr">src</span>=<span class="hljs-string" style="color: rgb(136, 0, 0);">"core.js"</span>&gt;</span><span class="undefined"></span><span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">script</span>&gt;</span>
	<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">body</span>&gt;</span>
<span class="hljs-tag">&lt;/<span class="hljs-name" style="font-weight: 700;">html</span>&gt;</span></span></pre>'`;
